name = "buffer-woes"
main = "worker-site/worker.mjs"
usage_model = "bundled"
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-06-02"

[build]
command = "npm run build"

[site]
bucket = ".svelte-kit/assets"